### PR TITLE
add file for matlab/julia version comparison

### PR DESCRIPTION
**Pull request by ReneSkukies**
@behinger 

The code inside the file works now (on the server). I was not sure which data/ formula you wanted to benchmark, but you can quickly change that I think and test it out yourself =)

### CODE REVIEW

**Comment by behinger** [comment]
Great! I thought of a 

2x2x2 design:

 simple model vs lots of spline-predixtors (like4-5)

And 
Little data, 5min at 100hz and more data 60min at 500hz

One channel vs. 30 channels.

For the 30 channels we could just repeat the same channel and add fresh noise. We could also use Multichannel component to simulate something realistic


I will not have time to work on it, does it fit into your interest? You could add it to the paper & provide an (identical/similar) documentation page



Am 21. November 2023 15:43:45 MEZ schrieb "René Skukies" ***@***.***>:

**Comment by behinger** [comment]
Too many comparisons? Or maybe just ok. We might not need all comparisons but rather choose reasonable defaults

**Comment by ReneSkukies** [comment]
Now has:
One channel with sfreq=100, and formula 1+condition+spl(continuous,5)

Multi-channel based on HartMut with sfreq=100, and formula 1+condition+spl(continuous,5) (same design as for one channel)

**Comment by behinger** [comment]
what is the status of this one?

**Comment by ReneSkukies** [comment]
Comparison works (on the server, since the MATLAB version, plus eeglab/ unfold MATLAB have to be specified as path); functions and scripts are separated;

Current measure for the multichannel data: MATLAB 68sec, Julia 20threads 15sec, Julia GPU 11 sec

We wanted to talk about a more complex example in our meeting though. I.e. higher sfreq and more covariates.

**Pull request closed without merging**
