### PR TITLE
predict tutorial

### PR DESCRIPTION
**Pull request by behinger**
- **up predict.jl**
- **add assert**
- **Update src/predict.jl**
- **Update src/predict.jl**
- **rename variable**
- **Update src/predict.jl**
- **update assert in predict.jl**
- **minor predict improvements**

### CODE REVIEW

**Review by ReneSkukies — APPROVED** [review]
Mainly some typos and I rewrote some stuff for better understandability. Otherwise looks good =)

**Comment by behinger** [comment]
nice thanks! I think if you do a "review" next time, I could accept all of them at once; but I'm not sure - aybe you even did that :)

**Comment by ReneSkukies** [comment]
> nice thanks! I think if you do a "review" next time, I could accept all of them at once; but I'm not sure - aybe you even did that :)

That is indeed what I did :')

**Comment by behinger** [comment]
Damn alright - very annoying I had to accept each commit on its own. Maybe I didn't see it

**Pull request merged**
